apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-sum-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-sum-python
  template:
    metadata:
      labels:
        app: two-sum-python
    spec:
      containers:
        - name: two-sum-python
          image: gcr.io/leetcode-377114/two_sum-python:v3
          ports:
            - containerPort: 8080
