# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: two-sum-python-service
spec:
  selector:
    app: two-sum-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
