name: Autodeploy

on:
  push:
    branches:
      - main
      
env:
  VPS_IP: ${{ secrets.VPS_IP }}
  VPS_USER: root
  VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Connect to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.VPS_IP }}
        username: ${{ env.VPS_USER }}
        password: ${{ env.VPS_PASSWORD }}
        script: |
          echo Pulling latest changes from Git
          cd /root/backend-api
          git pull
